name       : menulibre
version    : 2.1.3
release    : 1
source     :
    - https://launchpad.net/menulibre/2.1/2.1.3/+download/menulibre-2.1.3.tar.gz : bdd69740119902f1b1f8c7831155f4428403792a0a6c4287bcbb395c4e71fb31
license    : GPL-2.0
summary    : Advanced menu editor
component  : desktop
description: |
    An advanced menu editor that provides modern features in a clean, easy-to-use interface. All without GNOME dependencies, so even lightweight systems can benefit from the sanity that MenuLibre offers. MenuLibre is your one-stop shop for menus in Linux, whether you use Gnome, LXDE, XFCE, or Unity.
builddeps  :
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(gtk+-3.0)
    - xdg-utils
    - python-psutil
    - python-distutils-extra
rundeps    :
    - python-psutil
    - python-distutils-extra
    - python3
    - libgnome-menus
build      : |
    python3 setup.py build
install    : |
    python3 setup.py install --root=%installroot% --no-compile -O0
