name       : menulibre
version    : 2.2.1
release    : 7
source     :
    - https://launchpad.net/menulibre/2.2/2.2.1/+download/menulibre-2.2.1.tar.gz : 5b3ef8e6073d584f6accf282fa1eb649185ee42eb22fab70231491c7377d7e8f
license    : GPL-3.0-only
component  : desktop
summary    : Advanced menu editor
description: |
    An advanced menu editor that provides modern features in a clean, easy-to-use interface. All without GNOME dependencies, so even lightweight systems can benefit from the sanity that MenuLibre offers. MenuLibre is your one-stop shop for menus in Linux, whether you use Gnome or Budgie.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-distutils-extra
    - python-psutil
    - xdg-utils
rundeps    :
    - libgnome-menus
    - python3
    - python-distutils-extra
    - python-psutil
setup      : |
    %patch -p1 < $pkgfiles/0002-Should-only-be-visible-on-Gnome-and-Budgie.patch
build      : |
    %python3_setup
install    : |
    %python3_install
