name       : menulibre
version    : 2.1.5
release    : 4
source     :
    - https://launchpad.net/menulibre/2.1/2.1.5/+download/menulibre-2.1.5.tar.gz : ef05b2722bab2acb7070d6c8ed0e7bd58bd4a4540bf498af9e889944f9da08b5
license    : GPL-3.0
component  : desktop
summary    : Advanced menu editor
description: |
    An advanced menu editor that provides modern features in a clean, easy-to-use interface. All without GNOME dependencies, so even lightweight systems can benefit from the sanity that MenuLibre offers. MenuLibre is your one-stop shop for menus in Linux, whether you use Gnome, LXDE, XFCE, or Unity.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-distutils-extra
    - python-psutil
    - xdg-utils
rundeps    :
    - libgnome-menus
    - python3
    - python-distutils-extra
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
