name       : menulibre
version    : 2.3.1
release    : 13
source     :
    - https://github.com/bluesabre/menulibre/releases/download/menulibre-2.3.1/menulibre-2.3.1.tar.gz : 191d1ea7a3d6e61093f47e3f898428258fcec35e471e1fcab97965a6b79bf0a4
license    : GPL-3.0-only
homepage   : https://bluesabre.org/menulibre/
component  : desktop
summary    : Advanced menu editor
description: |
    An advanced menu editor that provides modern features in a clean, easy-to-use interface. All without GNOME dependencies, so even lightweight systems can benefit from the sanity that MenuLibre offers. MenuLibre is your one-stop shop for menus in Linux, whether you use Gnome or Budgie.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-distutils-extra
    - python-psutil
    - xdg-utils
rundeps    :
    - libgnome-menus
    - python-gobject
    - python-psutil
    - xdg-utils
setup      : |
    %patch -p1 < $pkgfiles/0002-Should-only-be-visible-on-Gnome-and-Budgie.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rv $installdir/usr/share/doc

    # Don't need uninstall script
    rm -rf $installdir/usr/lib/python3.10/site-packages/uninstall.py
