name       : menulibre
version    : 2.2.3
release    : 11
source     :
    - https://github.com/bluesabre/menulibre/releases/download/menulibre-2.2.3/menulibre-2.2.3.tar.gz : 58ed228f066fa92c1c7889949d218f89a2e1505cd73e843409dfb5e6f2aedb4a
license    : GPL-3.0-only
homepage   : https://bluesabre.org/menulibre/
component  : desktop
summary    : Advanced menu editor
description: |
    An advanced menu editor that provides modern features in a clean, easy-to-use interface. All without GNOME dependencies, so even lightweight systems can benefit from the sanity that MenuLibre offers. MenuLibre is your one-stop shop for menus in Linux, whether you use Gnome or Budgie.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - python-distutils-extra
    - python-psutil
    - xdg-utils
rundeps    :
    - libgnome-menus
    - python-gobject
    - python-psutil
    - xdg-utils
setup      : |
    %patch -p1 < $pkgfiles/0002-Should-only-be-visible-on-Gnome-and-Budgie.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rv $installdir/usr/share/doc

    # Remove duplicate metainfo file
    rm -r $installdir/usr/share/menulibre/metainfo
